[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.5"

# The title and description fields are primarily for displaying extension info in UI
title = "solar panels INFO"
description="This extension provides a digital panel to visualize specific properties of solar panels imported from GH Ladybug."

# Path (relative to the root) or content of readme markdown file for UI.
icon = "data/icon.png"
preview_image = "data/preview.jpg" 
readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
# repository = "https://github.com" 

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords =  ["kit", "AEC", "BIM", "Digital Twins", "Data Visualization", "Energy Saving", "Carbon Emissions", "Sunlight Radiation",
"Grasshopper","Ladybug", "HNADI", "HC"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import omni.tools.quick_array".
[[python.module]]
name = "hnadi.tools.solarpanels_info" 